//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.34209
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ScanUnits {

    private List<Unit> unitField;
    
    [System.Xml.Serialization.XmlElementAttribute("Unit")]
    public List<Unit> Units
    {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class Unit {
    
    private string locationField;
    
    private string urIpAddressField;

    private string rdIpAddressField;

    private string vfAddressField;
    
    private string projectNameField;
    
    private int majorversionField;
    
    private int minorversionField;
    
    private int svnRevisionField;
    
    private string buildDateField;
    
    private string idField;
    
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    public string urIpAddress {
        get {
            return this.urIpAddressField;
        }
        set {
            this.urIpAddressField = value;
        }
    }

    public string rdIpAddress
    {
        get
        {
            return this.rdIpAddressField;
        }
        set
        {
            this.rdIpAddressField = value;
        }
    }

    public string vfIpAddress
    {
        get
        {
            return this.vfAddressField;
        }
        set
        {
            this.vfAddressField = value;
        }
    }

    public string projectName {
        get {
            return this.projectNameField;
        }
        set {
            this.projectNameField = value;
        }
    }
    
    public int majorversion {
        get {
            return this.majorversionField;
        }
        set {
            this.majorversionField = value;
        }
    }
    
    public int minorversion {
        get {
            return this.minorversionField;
        }
        set {
            this.minorversionField = value;
        }
    }
    
    public int svnRevision {
        get {
            return this.svnRevisionField;
        }
        set {
            this.svnRevisionField = value;
        }
    }
    
    public string buildDate {
        get {
            return this.buildDateField;
        }
        set {
            this.buildDateField = value;
        }
    }
    
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}
